[haiku]
name = "haiku_example"

[haiku.metadata]
torii_url = "http://localhost:8080"
rpc_url = "http://localhost:5050"
world_address = "0x34d4e2fcecd511a3286e6acc3e0108ff5d6b7e9290876f988a76163ade950b2"
relay_url = "/ip4/127.0.0.1/udp/9090/quic-v1"
database_url = "haiku.db"
signer_address = "0x0101010101010101010101010101010101010101010101010101010101010101"
signer_public_key = "0x0101010101010101010101010101010101010101010101010101010101010101"
signer_private_key = "0x0101010101010101010101010101010101010101010101010101010101010101"

[haiku.llm]
chat_completion_provider = "ollama"
ai_model = "haiku"
ai_url = "http://localhost:11434/api/generate"
ai_token = ""

embedding_provider = "baai-bge"
embedding_model = ""
embedding_url = "https://api-inference.huggingface.co/models/BAAI/bge-small-en-v1.5"
embedding_token = ""

[haiku.db_config]
vector_size = "1536"
number_memory_to_retrieve = "1"

[haiku.context]
story = """The game is a dungeon crawler."""

[[events]]
tag = "dojo_examples-Moved"

[events.prompt]
template = """The player ${player} is moving ${direction}."""

[events.db_keys]
storage_keys = [
    "player",
]
retrieval_keys = [
    "player",
]

[[events.keys_mapping]]
key = "slip"
alias = "player"

[[events.keys_mapping]]
key = "target_entity_id"
alias = "player"
