kind = "DojoModel"
class_hash = "0x2cb22c61577afc5f6c2977f2c40f005aa67d96524cbb0e925607c23e10a718e"
original_class_hash = "0x2cb22c61577afc5f6c2977f2c40f005aa67d96524cbb0e925607c23e10a718e"
abi = "manifests/dev/base/abis/models/dojo_starter_rpg-Player-12268099.json"
tag = "dojo_starter_rpg-Player"
qualified_path = "rpg::models::index::player"
manifest_name = "dojo_starter_rpg-Player-12268099"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "mode"
type = "u8"
key = false

[[members]]
name = "role"
type = "u8"
key = false

[[members]]
name = "damage"
type = "u8"
key = false

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "gold"
type = "u16"
key = false

[[members]]
name = "score"
type = "u16"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false

[[members]]
name = "name"
type = "felt252"
key = false
